version: '3'

includes:
  abi_generator:
    taskfile: ./abi-generator/Taskfile.yml
    dir: ./abi-generator
  backend:
    taskfile: ./shingitai-backend/Taskfile.yml
    dir: ./shingitai-backend
  indexer:
    taskfile: ./shingitai-indexer/Taskfile.yml
    dir: ./shingitai-indexer
  backoffice:
    taskfile: ./shingitai-backoffice/Taskfile.yml
    dir: ./shingitai-backoffice
  member:
    taskfile: ./shingitai-member/Taskfile.yml
    dir: ./shingitai-member
  tools:
    taskfile: ./shingitai-tools/Taskfile.yml
    dir: ./shingitai-tools
  certificate:
    taskfile: ./shingitai-certificate/Taskfile.yml
    dir: ./shingitai-certificate

tasks:
  update-abi:
    desc: Update the ABI everywhere.
    cmds:
      - task: abi_generator:default
      - cp abi-generator/src/generated.ts shingitai-certificate/src/generated.ts
      - cp abi-generator/src/generated.ts shingitai-indexer/abis/generated.ts
      - cp abi-generator/src/generated.ts shingitai-backend/scripts/generated.ts
      - cp abi-generator/src/generated.ts shingitai-member/src/generated.ts
      - cp abi-generator/src/generated.ts shingitai-validator/src/generated.ts
      - cp abi-generator/src/generated.ts shingitai-backoffice/src/generated.ts
    sources:
      - abi-generator/src/generated.ts
    run: when_changed
    method: timestamp
  all:install:dependencies:
    desc: Install the dependencies for each project
    cmds:
      - task: abi_generator:install:dependencies
      - task: backend:install:dependencies
      - task: indexer:install:dependencies
      - task: backoffice:install:dependencies
      - task: member:install:dependencies
      - task: tools:install:dependencies
      - task: certificate:install:dependencies
  github:actions:
    desc: Run the Github Actions with act
    cmds:
      - act --container-architecture linux/amd64